### ISSUE TITLE
Do not send messages to a destroyed socket stream

### ISSUE THREAD

**Issue by cwysong85** [cwysong85/msrp-node-lib#10]
If a socket is destroyed during a re-INVITE event, heartbeats are still trying to be sent to a destroyed socket. A simple socket.destroyed check should be invoked before sending anything down the socket stream.

https://nodejs.org/api/net.html#net_socket_destroyed

**Comment by luisviman** [comment]
Fixed. An error log will be printed when trying to write to a destroyed socket. This fix will be included in msrp-node-lib 0.0.31.
